---
kind: pipeline
type: docker
name: integrate

platform:
  os: linux
  arch: amd64

steps:
- name: unit test app
  image: golang
  commands:
  - curl https://gotest-release.s3.amazonaws.com/gotest_linux > gotest && chmod +x gotest
  - ./gotest ./... -v
- name: build app
  image: docker:latest
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock
  commands:
    - sudo docker build -t gregentoo/remindme .
    - sudo docker push gregentoo/remindme:${DRONE_COMMIT_SHA}
    - sudo docker push gregentoo/remindme:latest
  #when:
  #  branch: master
  #  event: push

      #DRONE_COMMIT_SHA

trigger:
  event: [ push ]

