---
kind: pipeline
type: docker
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: unit test app
  image: golang
  commands:
  - curl https://gotest-release.s3.amazonaws.com/gotest_linux > gotest && chmod +x gotest
  - ./gotest ./... -v
---
kind: pipeline
type: docker
name: deploy

platform:
  os: linux
  arch: amd64

steps:
- name: build and push image to Docker hub
  image: plugins/docker
  password:
      from_secret: DOCKER_HUB_PWD
  settings: 
    username: gregentoo
    password:
      from_secret: DOCKER_HUB_PWD
    repo: gregentoo/remindme
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - main
#- name: deploy
#  image: docker/compose:1.25.0-rc2-alpine
#  command:
#    - docker-compose -f ./docker-compose.yml up -d
#  volumes:
#    - name: dockersock
#      path: /var/run/docker.sock
#  when:
#    branch:
#    - main