---
kind: pipeline
type: docker
name: integrate

platform:
  os: linux
  arch: amd64

steps:
- name: unit test app
  image: golang
  commands:
  - curl https://gotest-release.s3.amazonaws.com/gotest_linux > gotest && chmod +x gotest
  - ./gotest ./... -v
- name: build app
  image: plugins/docker
  environment:
    TOKEN:
      from_secret: DOCKER_HUB_TOKEN
    PASSWORD:
      from_secret: DOCKER_HUB_PWD
  settings: 
    username: gregentoo
    password: DOCKER_HUB_PWD
    repo: gregentoo/remindme
    build_args_from_env:
      - TOKEN
    tags:
      - latest
      - ${DRONE_COMMIT_SHA}
  when:
    event: push
  #  branch: master