version: "3.6"

services:
  bot:
    image: gregentoo/remindme:${TAG}
    #build:
    #  context: .
    container_name: bot
    restart: always
    ports:
      - 8002:8002
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REMINDME_DB_PASSWORD=${REMINDME_DB_PASSWORD}
      - REMINDME_DB_HOST=${REMINDME_DB_HOST}
      - REMINDME_DB_DSN=${REMINDME_DB_DSN}
      - GRAYLOG_ENDPOINT=${GRAYLOG_ENDPOINT}
      - DB_MIGRATIONS_DIR=${DB_MIGRATIONS_DIR}
      - TZ=Europe/Berlin
networks: 
  default: 
    external: 
      name: graylog