version: "3.6"

services:
  bot:
    image: gregentoo/remindme:latest
    container_name: bot
    restart: always
    ports:
      - 8002:8002
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
