version: "3.6"

services:
  bot:
    image: gregentoo/remindme:${TAG}
    container_name: bot
    restart: always
    ports:
      - 8002:8002
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
#    depends_on:
#      - storage
#  storage:
#    image: postgres:${POSTGRESQL_VERSION}
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
#      timeout: 45s
#      interval: 10s
#      retries: 10
#    restart: always
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - REMINDER_DB_NAME=${REMINDER_DB_NAME}
#      - REMINDER_DB_USER=${REMINDER_DB_USER}
#      - REMINDER_DB_PASSWORD=${REMINDER_DB_PASSWORD}
#    volumes:
#      - ./db:/docker-entrypoint-initdb.d/
#      - /var/lib/postgresql/data
#    ports:
#      - 5433:5432
