#!/bin/bash

export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $REMINDER_DB_USER WITH PASSWORD '$REMINDER_DB_PASSWORD';
  CREATE DATABASE $REMINDER_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $REMINDER_DB_NAME TO $REMINDER_DB_USER;
  \connect $REMINDER_DB_NAME $REMINDER_DB_USER
  BEGIN;
    CREATE TABLE IF NOT EXISTS reminder (
	  id serial PRIMARY KEY,
	  chat_id INT NOT NULL,
      text VARCHAR NOT NULL,
      recurrent_day VARCHAR(20) DEFAULT NULL,
      target_date date,
      target_time time NOT NULL
	);
  COMMIT;
EOSQL